### ISSUE TITLE
Intensity profile in HAADF image in arbitrary direction

### ISSUE THREAD

**Issue by L-Fr** [din14970/TEMMETA#5]
If a line profile is chosen to go into any arbitrary direction (not vertical or horizontal), by using x2,y2 values which remain the same vector length as in a horizontal direction, the total length of the line profile seems to be not as long as if it is chosen to be in a horizontal direction-and also it is visible in the intensity profile that the vector is ending earlier than it is supposed to be according to the x2,y2  inserted values.

**Comment by din14970** [comment]
This should now be finally fixed in version 0.0.5
