### ISSUE TITLE
plt.show()

### ISSUE THREAD

**Issue by jan-janssen** [din14970/TEMMETA#7]
I have trouble to overlay some information over existing data, because each plot command directly shows the image: 
https://github.com/din14970/TEMMETA/blob/master/temmeta/plottingtools.py#L384

**Comment by jan-janssen** [comment]
Here is an example of overlaying the segmentation from Ning, this is only possible if the plotting `plt.show()` is removed:
https://github.com/NingWang1990/pyiron-pystem-temmeta/blob/master/tem.ipynb
For now this is fixed in: https://github.com/NingWang1990/pyiron-pystem-temmeta/blob/master/tem.py#L132

**Comment by din14970** [comment]
This should now be fixed, I just removed what you commented out.
